server:
  port: 8081
#db configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp_api
    username: root
    password: Password@09
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# create, create-drop,update,validate
        ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
